name: release-tools
on:
  push:
    tags:
      - 'tools-*'
env:
  tag: ${GITHUB_REF#refs/tags/tools-}
jobs:
  release-cke-tools:
    name: Release CKE tools image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Build CKE tools
        run: |
          cd tools
          make all
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push cke-tools
        uses: docker/build-push-action@v5
        with:
          context: ./tools
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/cke-tools:${{ env.tag }}
          labels: org.opencontainers.image.source=https://github.com/${{ github.repository }}
