name: release
on:
  push:
    tags:
      - 'v*'
env:
  tag: ${GITHUB_REF#refs/tags/v}
  prerelease: ${{ contains(github.ref, '-') }}
jobs:
  sonobuoy:
    name: Run sonobuoy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: |
          echo "hello" > /tmp/sonobuoy.txt
      - name: Upload sonobuoy test result
        uses: actions/upload-artifact@v3
        with:
          name: sonobuoy-test
          path: /tmp/sonobuoy.txt
          retention-days: 1
  release-cke-image:
    name: Release CKE Image
    needs: sonobuoy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push cke-tools
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: ${{ !env.prerelease }}
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/cke:${{ env.tag }}
          labels: org.opencontainers.image.source=https://github.com/${{ github.repository }}
  release-github:
    name: Release on GitHub
    runs-on: ubuntu-22.04
    needs: release-cke-image
    steps:
      - uses: actions/checkout@v4
      - name: Download sonobuoy test
        uses: actions/download-artifact@v3
        with:
          name: sonobuoy-test
      - name: Prepare files
        run: |
          mkdir /tmp/upload
          cp ./sonobuoy.tar.gz /tmp/upload
          tar xzf ./sonobuoy.tar.gz -C /tmp/upload --strip-components=4 plugins/e2e/results/global/e2e.log plugins/e2e/results/global/junit_01.xml
          sed "s/vX\.Y\.Z/v${{ env.tag }}/" sonobuoy/README.md > /tmp/upload/README.md
          sed "s/vX\.Y\.Z/v${{ env.tag }}/" sonobuoy/PRODUCT.yaml > /tmp/upload/PRODUCT.yaml
          GOBIN=/tmp/upload CGO_ENABLED=0 go install -buildvcs=false ./pkg/cke ./pkg/ckecli
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ${{ env.prerelease }}; then
            PRERELEASE="--prerelease"
          fi
          gh release create v${{ env.tag }} ${PRERELEASE} -t v${{ env.tag }}  -n "See [CHANGELOG.md](./CHANGELOG.md) for details." /tmp/upload/
